version: 2

models:
  - name: int_session_length
    description: For each session, when did the first and last event take place?
    columns:
      - name: session_id
        tests:
          - not_null
          - unique
      - name: first_event
        tests:
          - not_null
      - name: last_event
        tests:
          - not_null

  - name: int_user_session_activity
    description: A table tracking web page activity on Greenery for each session and user.
    columns:
      - name: session_id
        tests:
          - not_null
      - name: user_id
        tests:
          - not_null      
  
  - name: fct_user_sessions
    description: A table tracking webpage activity for each session but now joined with many user dimensions.
    columns:
      - name: session_id
        tests:
          - not_null
      - name: user_id
        tests:
          - not_null
      - name: session_length_minutes
        tests:
          - not_null
          - positive_values
  
  - name: conversions_by_product
    description: Tracking conversion rates across Greenery's product catalog
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
  
  - name: product_funnel
    description: Tracking session volume through product funnel.

exposures:
  
  - name: Product Funnel Dashboard
    type: dashboard
    maturity: low
    # url: https://bi.tool/dashboards/1
    description: >
      Tracking the volume of users moving through Greenery's product
      funnel which levels have the largest drop points. 
    
    depends_on:
      - ref('product_funnel')
      
    owner:
      name: Callum
      email: callum@sidekickhealth.com
